// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHlaePQx74Jcs_M32WRY9CAHikoVad8nU',
    appId: '1:934618428636:web:4841cb968cf924aa9e3019',
    messagingSenderId: '934618428636',
    projectId: 'fruitsfruits-market-a1d85',
    authDomain: 'fruitsfruits-market-a1d85.firebaseapp.com',
    storageBucket: 'fruitsfruits-market-a1d85.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5zNXdWhmSwQ5A2AwbSRXdxErWEpe5kW0',
    appId: '1:934618428636:android:877eb357d07ec22e9e3019',
    messagingSenderId: '934618428636',
    projectId: 'fruitsfruits-market-a1d85',
    storageBucket: 'fruitsfruits-market-a1d85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1YZXG7aRk110v881xnxBfjsocma1Le_8',
    appId: '1:934618428636:ios:e0c7a6d7135908e29e3019',
    messagingSenderId: '934618428636',
    projectId: 'fruitsfruits-market-a1d85',
    storageBucket: 'fruitsfruits-market-a1d85.firebasestorage.app',
    iosBundleId: 'com.example.fruitsMarket',
  );
}
